pipeline {
  agent any
    
  stages {
	stage('Clone') {
		steps {
	  		sh 'rm -rf calend4r'
        	sh 'git clone https://heroku:${HEROKU_TOKEN}@git.heroku.com/calend4r.git'
		}
	}

	stage('Copy') {
		steps {
			sh 'rm -rf ./calend4r/app'
			sh 'cp -r app ./calend4r'
		}
	}

	stage('Deliver') {
		steps {
			dir('./calend4r') {
				sh 'git add .'
				sh 'git commit -m"jenkins"'
				sh 'git push'
			}
		}
	}

  }
}


